[package]
name = "my_solana_program"
version = "0.1.0"
description = "My Solana program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "my_solana_program"

[dependencies]
anchor-lang = "0.32.1"
