name: Build Solana Program

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libudev-dev libssl-dev build-essential curl wget

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        
    - name: Install Solana
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        
    - name: Install Anchor
      run: |
        # libudev sorununu çözmek için environment variables ayarla
        export RUSTFLAGS="-C link-arg=-Wl,--allow-multiple-definition"
        cargo install --locked anchor-cli
      
    - name: Build program
      run: anchor build
