name: Build Solana Program

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        
    - name: Install Solana
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        
    - name: Install Anchor
      run: cargo install --locked anchor-cli
      
    - name: Build program
      run: anchor build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solana-program
        path: |
          target/**/*.so
          target/idl/**/*
        retention-days: 30
